name: React CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  react-deploy:
    runs-on: ubuntu-latest
    steps:
      # 체크아웃 -> 깃허브의 저장소로부터 소스 체크아웃
      - name: Checkout repository resource
        uses: action/checkout@v2
      # 환경변수 동적 생성 -> .env
      - name: .env 환경 변수 동적 생성
        run: |
          echo "${{ secrets.CLIENT_ENV }}" > .env
          pwd
          ls -al
      # 빌드를 위한 조건 -> nodejs 설치
      # npm install 라이브러리 설치
      # 빌드의 결과물을 ec2로 업로드
      # 뒷 정리(업로드 결과 -> nginx의 root로 이동(설정), 디렉토리 정리)
