name: React CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  react-deploy:
    runs-on: ubuntu-latest
    steps:
      # 체크아웃 -> 깃허브의 저장소로부터 소스 체크아웃
      - name: Checkout repository resource
        uses: actions/checkout@v2

      # 환경변수 동적 생성 -> .env
      - name: .env 환경 변수 동적 생성
        run: |
          echo "${{ secrets.CLIENT_ENV }}" > .env
          pwd
          ls -al

      # 빌드를 위한 조건 -> nodejs 설치
      - name: nodejs 설치
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      # npm install 라이브러리 설치
      - name: install 독립 라이브러리
        run: npm install

      # 빌드
      - name: 빌드
        run: |
          npm run build
          ls ./build

      # 빌드의 결과물을 ec2로 업로드
      - name: EC2에 빌드된 파일/폴더들 업로드
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: ./build/*
          target: /home/ubuntu/client

      # 뒷 정리(업로드 결과 -> nginx의 root로 이동(설정), 디렉토리 정리)
      # - name: 뒷 정리
